# strings in tensorflow

In [5]:
import tensorflow as tf


In [6]:
string=tf.constant("deep learning")
print(string)

tf.Tensor(b'deep learning', shape=(), dtype=string)


In [9]:
tf.strings.upper(string)

<tf.Tensor: shape=(), dtype=string, numpy=b'DEEP LEARNING'>

In [10]:
tf.strings.lower(string)

<tf.Tensor: shape=(), dtype=string, numpy=b'deep learning'>

In [12]:
tf.strings.split("hello world")

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'hello', b'world'], dtype=object)>

In [14]:
tf.strings.unicode_decode(string,"UTF8")

<tf.Tensor: shape=(13,), dtype=int32, numpy=array([100, 101, 101, 112,  32, 108, 101,  97, 114, 110, 105, 110, 103])>

In [20]:
list_array=tf.constant(["tensorflow","deep learning","pytorch"])
for i in list_array:
    print(i)

tf.Tensor(b'tensorflow', shape=(), dtype=string)
tf.Tensor(b'deep learning', shape=(), dtype=string)
tf.Tensor(b'pytorch', shape=(), dtype=string)


In [21]:
tf.strings.to_number("66")


<tf.Tensor: shape=(), dtype=float32, numpy=66.0>

# Reduce Functions
In the implementation of the neural network, we may need to reduce a tensor into a single value. Thus, this single value will reflect the complete tensor for the next layers or output of a neural network.

In [24]:
feat_value=tf.constant([[1,12],[2,13],[3,14]])
pred=tf.reduce_sum(feat_value)
print(pred)

tf.Tensor(45, shape=(), dtype=int32)


In [25]:
print(tf.reduce_sum(feat_value, 0))

tf.Tensor([ 6 39], shape=(2,), dtype=int32)


In [26]:
print(tf.reduce_sum(feat_value, 1))

tf.Tensor([13 15 17], shape=(3,), dtype=int32)


In [32]:
print(tf.reduce_max(feat_value))

tf.Tensor(14, shape=(), dtype=int32)


# Reshape
The neural networks are widely used for image processing, however, an image is stored in the form of numeric values ranging between 0 to 255 in a matrix format. But, the neural network only accepts one-dimensional input so we need to reshape the input image into a one dimension tensor so that it can be fed to the neural network. Reshape function is useful to do so. In the code below, we created a simple grayscale image using random numbers and then converted this image into a linear tensor. The image below the code shows a pictorial representation of the idea for 2*2 image.

In [39]:
#we need to reshape a picture so that it can be feed to neural network
#lets say we have a 28*28 grayscale image
image=tf.random.uniform([28,28], maxval=255, dtype='int32')

image_reshape=tf.reshape(image, [28*28,1])
print(image_reshape)

tf.Tensor(
[[249]
 [243]
 [ 35]
 [166]
 [  1]
 [ 97]
 [  4]
 [130]
 [125]
 [142]
 [  0]
 [ 80]
 [129]
 [ 34]
 [133]
 [206]
 [253]
 [ 54]
 [112]
 [254]
 [ 90]
 [126]
 [ 88]
 [ 89]
 [212]
 [ 86]
 [ 99]
 [124]
 [246]
 [ 28]
 [ 47]
 [190]
 [208]
 [190]
 [212]
 [ 19]
 [ 35]
 [ 86]
 [ 91]
 [ 59]
 [131]
 [110]
 [171]
 [ 55]
 [ 63]
 [ 36]
 [168]
 [ 20]
 [140]
 [ 77]
 [121]
 [125]
 [125]
 [ 49]
 [ 85]
 [ 30]
 [  9]
 [100]
 [ 85]
 [215]
 [ 97]
 [ 50]
 [134]
 [  3]
 [132]
 [ 78]
 [ 75]
 [191]
 [ 13]
 [148]
 [ 61]
 [ 37]
 [ 97]
 [ 48]
 [143]
 [ 85]
 [233]
 [212]
 [142]
 [133]
 [ 58]
 [197]
 [ 55]
 [204]
 [ 53]
 [178]
 [204]
 [227]
 [114]
 [237]
 [102]
 [242]
 [224]
 [ 97]
 [201]
 [103]
 [190]
 [192]
 [181]
 [ 53]
 [ 84]
 [122]
 [ 39]
 [220]
 [ 10]
 [ 61]
 [131]
 [ 13]
 [174]
 [188]
 [160]
 [103]
 [142]
 [155]
 [175]
 [121]
 [ 27]
 [178]
 [ 32]
 [112]
 [ 47]
 [ 69]
 [ 77]
 [ 55]
 [  8]
 [ 57]
 [243]
 [187]
 [167]
 [ 35]
 [ 13]
 [193]
 [101]
 [103]
 [122]
 [225]
 [  3]
 [ 88]
 [196]
 [226]
 [ 16]
 [

# Gradient
When updating the weights of tensors in the neural network, we need to find the minimum, maximum, or optimal value of loss or other functions used. The gradient can help us to identify that because gradient equals to zero is optimal value, change in gradient is greater than zero we can further minimize the value and, lastly, the gradient is smaller than zero we can maximize the value. In simple language, gradient provides the rate of change in a variable depending on the change in another variable.

In [47]:
# Define x
x = tf.Variable(6.0)

# Define y within instance of GradientTape
with tf.GradientTape() as gt:
    gt.watch(x)
    y = tf.multiply(x, x)
    #Evaluate the gradient of y at x = 6
    g = gt.gradient(y, x)
    print(g.numpy())
   
    

12.0


In [46]:
# Define x
x = tf.Variable(6.0)

# Define y within instance of GradientTape
with tf.GradientTape() as gt:
    gt.watch(x)
   
  
    y=5*x
    g = gt.gradient(y, x)
    print(g.numpy())

5.0


In [48]:
# Define x
x = tf.Variable(5.0)

# Define y within instance of GradientTape
with tf.GradientTape() as gt:
    gt.watch(x)
    
   
  
    y=x*x*x
    g = gt.gradient(y, x)
    print(g.numpy())

75.0


In [50]:
x = tf.Variable(5.0)

# Define y within instance of GradientTape
with tf.GradientTape() as gt:
    gt.watch(x)
    with tf.GradientTape() as ggt:
        ggt.watch(x)
        y=x*x
        g1 = ggt.gradient(y, x)
    g2 = gt.gradient(g1, x)
        

In [51]:
print(g1)
print(g2)

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [54]:
x=tf.constant(4.0)
with tf.GradientTape(persistent=True) as gt:
    gt.watch(x)
    y=x*x
    z=y*y
dz_dx=gt.gradient(z,x)
dy_dx=gt.gradient(y,x)




In [55]:
print(dz_dx)
print(dy_dx)

tf.Tensor(256.0, shape=(), dtype=float32)
tf.Tensor(8.0, shape=(), dtype=float32)


# Thank you
## Author

<a href="https://www.linkedin.com/in/muhammad-bilal-afzal-95b33323b/">MUHAMMAD BILAL</a>